version: '3.3'

services:

  omeka_nickel:
    image: 270051160229.dkr.ecr.us-east-1.amazonaws.com/nickel
    networks:
      - traefik_proxy
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.backend=omeka_nickel"
        - "traefik.frontend.rule=Host:nickel.magnesium.coop"
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_proxy"
        - "traefik.backend.loadbalancer.sticky=true"
        - "traefik.frontend.passHostHeader=true"
      restart_policy:
        condition: on-failure

  omeka_db:
    image: mysql:5.7
    restart: always
    networks:
      - traefik_proxy
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka_nickel
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka
 
networks:
  traefik_proxy:
    external: true